// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from "@prisma/orm-postgres/adapter/operation-types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";
import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma/orm-postgres/target/codec-types";

export type StorageHash =
  StorageHashBase<"542ce1fe2d05a7dfe292c9e03150ed98a2629ed16ecb829ee12252c4cb891625">;
export type ExecutionHash =
  ExecutionHashBase<"de277f1434294aff6f76b96110c6a19731e90107c4bc4afa6f7ba73f114205a3">;
export type ProfileHash =
  ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "pg/int8@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "pg/int8@1"; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
      readonly "pg/date-string@1": { readonly output: "pg/date-string@1"; readonly nullable: true };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
      readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/text-array@1": { readonly output: "pg/text-array@1"; readonly nullable: true };
      readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/time-string@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
      readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
      readonly "pg/date-string@1": { readonly output: "pg/date-string@1"; readonly nullable: true };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
      readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/text-array@1": { readonly output: "pg/text-array@1"; readonly nullable: true };
      readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/time-string@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
      readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/unboundedint@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/unboundedint@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Message: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly threadId: CodecTypes["pg/text@1"]["output"];
      readonly role: CodecTypes["pg/text@1"]["output"];
      readonly content: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly Thread: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly userId: Char<36> | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly User: {
      readonly id: Char<36>;
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Message: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly threadId: CodecTypes["pg/text@1"]["input"];
      readonly role: CodecTypes["pg/text@1"]["input"];
      readonly content: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly Thread: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly userId: CodecTypes["sql/char@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly User: {
      readonly id: CodecTypes["sql/char@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"] | null;
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Message: {
      readonly content: CodecTypes["pg/text@1"]["output"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly role: CodecTypes["pg/text@1"]["output"];
      readonly threadId: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
    readonly Thread: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly title: CodecTypes["pg/text@1"]["output"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly userId: Char<36> | null;
    };
    readonly User: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
      readonly email: CodecTypes["pg/text@1"]["output"];
      readonly id: Char<36>;
      readonly name: CodecTypes["pg/text@1"]["output"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Message: {
      readonly content: CodecTypes["pg/text@1"]["input"];
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly role: CodecTypes["pg/text@1"]["input"];
      readonly threadId: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
    readonly Thread: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly title: CodecTypes["pg/text@1"]["input"];
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly userId: CodecTypes["sql/char@1"]["input"] | null;
    };
    readonly User: {
      readonly createdAt: CodecTypes["pg/timestamptz-string@1"]["input"];
      readonly email: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["sql/char@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"] | null;
      readonly updatedAt: CodecTypes["pg/timestamptz-string@1"]["input"];
    };
  };
};

export namespace Models {
  export type public_User = {
    id: Char<36>;
    email: CodecTypes["pg/text@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"] | null;
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    threads: public_Thread[];
    readonly [RelationKeys]?: "threads";
  };
  export type public_Thread = {
    id: CodecTypes["pg/text@1"]["output"];
    title: CodecTypes["pg/text@1"]["output"];
    userId: Char<36> | null;
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    user: public_User | null;
    messages: public_Message[];
    readonly [RelationKeys]?: "user" | "messages";
  };
  export type public_Message = {
    id: CodecTypes["pg/text@1"]["output"];
    threadId: CodecTypes["pg/text@1"]["output"];
    role: CodecTypes["pg/text@1"]["output"];
    content: CodecTypes["pg/text@1"]["output"];
    createdAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    updatedAt: CodecTypes["pg/timestamptz-string@1"]["output"];
    thread: public_Thread;
    readonly [RelationKeys]?: "thread";
  };
}

export declare const models: {
  public: {
    User: Models.public_User;
    Thread: Models.public_Thread;
    Message: Models.public_Message;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly Message: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly threadId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly content: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Thread: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: "literal";
                    readonly value: DefaultLiteralValue<"pg/text@1", "新会话">;
                  };
                };
                readonly userId: {
                  readonly nativeType: "character";
                  readonly codecId: "sql/char@1";
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly User: {
              columns: {
                readonly id: {
                  readonly nativeType: "character";
                  readonly codecId: "sql/char@1";
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly email: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                  readonly default: { readonly kind: "function"; readonly expression: "now()" };
                };
                readonly updatedAt: {
                  readonly nativeType: "timestamptz";
                  readonly codecId: "pg/timestamptz-string@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["email"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly User: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
    readonly Thread: { readonly namespace: "public" & NamespaceId; readonly model: "Thread" };
    readonly Message: { readonly namespace: "public" & NamespaceId; readonly model: "Message" };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Message: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly threadId: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly thread: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Thread";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["threadId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "Message";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly threadId: { readonly column: "threadId" };
                readonly role: { readonly column: "role" };
                readonly content: { readonly column: "content" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly Thread: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly userId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "sql/char@1";
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: { readonly namespace: "public" & NamespaceId; readonly model: "User" };
                readonly cardinality: "N:1";
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ["userId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly messages: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Message";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["threadId"];
                };
              };
            };
            readonly storage: {
              readonly table: "Thread";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly title: { readonly column: "title" };
                readonly userId: { readonly column: "userId" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "sql/char@1";
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/timestamptz-string@1";
                };
              };
            };
            readonly relations: {
              readonly threads: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "Thread";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["userId"];
                };
              };
            };
            readonly storage: {
              readonly table: "User";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly email: { readonly column: "email" };
                readonly name: { readonly column: "name" };
                readonly createdAt: { readonly column: "createdAt" };
                readonly updatedAt: { readonly column: "updatedAt" };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "Message";
            readonly column: "updatedAt";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "timestampNow" };
          readonly onUpdate: { readonly kind: "generator"; readonly id: "timestampNow" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "Thread";
            readonly column: "updatedAt";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "timestampNow" };
          readonly onUpdate: { readonly kind: "generator"; readonly id: "timestampNow" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "User";
            readonly column: "id";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "uuidv7" };
        },
        {
          readonly ref: {
            readonly namespace: "public";
            readonly table: "User";
            readonly column: "updatedAt";
          };
          readonly onCreate: { readonly kind: "generator"; readonly id: "timestampNow" };
          readonly onUpdate: { readonly kind: "generator"; readonly id: "timestampNow" };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
